### ISSUE TITLE
Change the dataset

### ISSUE THREAD

**Issue by Crustal0505** [yubowen-ph/JointER#3]
Hi! Sorry to bother you again. I am very interested in the work this paper. I want to replace the dataset with my own dataset, but I encountered the problem while processing my own data. Can you provide the code for preprocessing the dataset?

Thank you!

**Comment by yubowen-ph** [comment]
Sorry, I didn't save the data processing code, and I guess different raw data needs different processing code, so I suggest you convert your dataset according to the data format I provided.

**Comment by Crustal0505** [comment]
Thank you for responding to your busy schedule and I will accept your suggestions. Thanks again！





------------------ Original ------------------
