### ISSUE TITLE
How the EPO situation is handled? 

### ISSUE THREAD

**Issue by Freeshman** [yubowen-ph/JointER#5]
Hello, I'm studying your paper rencently. Your work is very great, but I didn't understand how the model handle the EPO situation from the paper's METHODOLOGY section. In fact, I think that tagging the relation label to indicate the start-end position in the TER stage can tag only one relation to a entity pair, so how to tag another relation for the same entity pair?  Could you give more details about it, thanks a lot.

**Comment by yubowen-ph** [comment]
Hi,
Thanks for your interest in this work. As pointed out in Section 3.2.3, ETL-Span cannot solve the problem of entity pair overlapping. But a sentence in the EPO set may contain multiple Normal and SEO triplets. In fact, even on the EPO set, there are still a significant amount of triplets where entity pairs don’t overlap, so ETL-Span can achieve competitive performance in this category.

Best regards,
Yu Bowen
