### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 131250208** [yubowen-ph/JointER#6]
Hi~, the paper claims that you use the datasets published by [CopyRE](https://github.com/xiangrongzeng/copy_re). They use the datasets only annotating the last word, do you also follow this preprocessing setting? Or do you preprocess on the original dataset released by [CopyRE](https://github.com/xiangrongzeng/copy_re) and annotate the whole span? Thanks for your reply~

**Comment by yubowen-ph** [comment]
Thanks for your interest. You are right, we preprocessed the original dataset and annotated the whole span. We think joint extraction needs to identify the whole entity rather than a single boundary word.
