### ISSUE TITLE
The trained model

### ISSUE THREAD

**Issue by liutianling** [yubowen-ph/JointER#9]
@yubowen-ph Hi yubowen.
If it is convenient  to share any of your trained model? Since I have no gpu to train yet, but i want to know the performance of the model myself.
Thanks a lot.

**Comment by yubowen-ph** [comment]
Sorry for the late reply, I'll upload the trained model later.

**Comment by liutianling** [comment]
@yubowen-ph Thank you for your reply!
In the code,  models/model.py, I can't find any information about relation ?
Such as the loss of relation（I don't know if it combine with obj..）, or any function return the relation?
Thank you again!

**Comment by yubowen-ph** [comment]
The task of relation classification has been converted into a object labelling problem, so its loss is obj_end_loss+ obj_end_loss in lines 82-83 in models/model.py

**Comment by liutianling** [comment]
Thanks for your replay! And I' m sorry for my careless.
